"""create_trading_metrics_table_for_grafana_integration

Revision ID: 5515ae92e630
Revises: 654f26037b5d
Create Date: 2025-12-06 20:15:37.222970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5515ae92e630'
down_revision: Union[str, Sequence[str], None] = '654f26037b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.DECIMAL(precision=18, scale=9), nullable=False),
    sa.Column('system_name', sa.String(length=50), nullable=False),
    sa.Column('execution_mode', sa.String(length=15), nullable=False),
    sa.Column('trader', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_metrics_metric_name'), 'trading_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_trading_metrics_system_name'), 'trading_metrics', ['system_name'], unique=False)
    op.create_index(op.f('ix_trading_metrics_timestamp'), 'trading_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_trading_metrics_trader'), 'trading_metrics', ['trader'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_metrics_trader'), table_name='trading_metrics')
    op.drop_index(op.f('ix_trading_metrics_timestamp'), table_name='trading_metrics')
    op.drop_index(op.f('ix_trading_metrics_system_name'), table_name='trading_metrics')
    op.drop_index(op.f('ix_trading_metrics_metric_name'), table_name='trading_metrics')
    op.drop_table('trading_metrics')
    # ### end Alembic commands ###
