"""Initial migration

Revision ID: 8b2f9aecf5ee
Revises: 
Create Date: 2025-10-09 23:48:43.487296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2f9aecf5ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mints',
    sa.Column('mint_address', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('symbol', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('mint_address')
    )
    op.create_table('traders',
    sa.Column('wallet_address', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('wallet_address')
    )
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fee_sol', sa.DECIMAL(precision=18, scale=9), nullable=True),
    sa.Column('total_cost_sol', sa.DECIMAL(precision=18, scale=9), nullable=True),
    sa.Column('signature', sa.String(length=100), nullable=True),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='side'), nullable=False),
    sa.Column('is_analyzed', sa.Boolean(), nullable=False),
    sa.Column('is_liquidation', sa.Boolean(), nullable=False),
    sa.Column('message_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('mints_id', sa.String(length=50), nullable=False),
    sa.Column('traders_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['mints_id'], ['mints.mint_address'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['traders_id'], ['traders.wallet_address'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signature')
    )
    op.create_index(op.f('ix_positions_mints_id'), 'positions', ['mints_id'], unique=False)
    op.create_index(op.f('ix_positions_traders_id'), 'positions', ['traders_id'], unique=False)
    op.create_table('open_positions',
    sa.Column('positions_id', sa.UUID(), nullable=False),
    sa.Column('sol_amount_sent', sa.DECIMAL(precision=18, scale=9), nullable=False),
    sa.Column('sol_amount_executed', sa.DECIMAL(precision=18, scale=9), nullable=True),
    sa.Column('token_amount_received', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'PARTIALLY_CLOSED', 'CLOSED', 'FAILED', name='openpositionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['positions_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('positions_id')
    )
    op.create_table('trader_trade_data',
    sa.Column('positions_id', sa.UUID(), nullable=False),
    sa.Column('sol_amount', sa.DECIMAL(precision=18, scale=9), nullable=False),
    sa.Column('token_amount', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('new_token_balance', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('signature', sa.String(length=100), nullable=False),
    sa.Column('pool', sa.String(length=15), nullable=False),
    sa.Column('bonding_curve_key', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['positions_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('positions_id')
    )
    op.create_table('close_orders',
    sa.Column('positions_id', sa.UUID(), nullable=False),
    sa.Column('open_positions_id', sa.UUID(), nullable=True),
    sa.Column('token_amount_sent', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('sol_amount_received', sa.DECIMAL(precision=18, scale=9), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'SUCCESS', 'FAILED', name='closeorderstatus'), nullable=False),
    sa.ForeignKeyConstraint(['open_positions_id'], ['open_positions.positions_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['positions_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('positions_id')
    )
    op.create_table('partial_close_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('close_orders_id', sa.UUID(), nullable=False),
    sa.Column('open_positions_id', sa.UUID(), nullable=True),
    sa.Column('token_amount_sent', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('sol_amount_received', sa.DECIMAL(precision=18, scale=9), nullable=True),
    sa.Column('total_cost_sol', sa.DECIMAL(precision=18, scale=9), nullable=True),
    sa.Column('message_error', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='partialcloseorderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['close_orders_id'], ['close_orders.positions_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['open_positions_id'], ['open_positions.positions_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partial_close_orders')
    op.drop_table('close_orders')
    op.drop_table('trader_trade_data')
    op.drop_table('open_positions')
    op.drop_index(op.f('ix_positions_traders_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_mints_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('traders')
    op.drop_table('mints')
    # ### end Alembic commands ###
