"""Add copy trading bots, runs and update schema

Revision ID: b614db408750
Revises: 8b2f9aecf5ee
Create Date: 2025-10-20 14:49:02.541102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b614db408750'
down_revision: Union[str, Sequence[str], None] = '8b2f9aecf5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copy_trading_bots',
    sa.Column('system_wallet_address', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('system_wallet_address')
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_dry_run', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('copy_trading_bots_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['copy_trading_bots_id'], ['copy_trading_bots.system_wallet_address'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_copy_trading_bots_id'), 'runs', ['copy_trading_bots_id'], unique=False)
    op.create_table('run_mints',
    sa.Column('runs_id', sa.UUID(), nullable=False),
    sa.Column('mints_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['mints_id'], ['mints.mint_address'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runs_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('runs_id', 'mints_id')
    )
    op.create_table('run_traders',
    sa.Column('runs_id', sa.UUID(), nullable=False),
    sa.Column('traders_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['runs_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traders_id'], ['traders.wallet_address'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('runs_id', 'traders_id')
    )
    op.add_column('mints', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('mints', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('mints', 'name',
                existing_type=sa.VARCHAR(length=30),
                type_=sa.String(length=40),
                existing_nullable=True)
    op.add_column('positions', sa.Column('runs_id', sa.UUID(), nullable=False))
    op.alter_column('positions', 'traders_id',
                existing_type=sa.VARCHAR(length=50),
                nullable=True)
    op.create_index(op.f('ix_positions_runs_id'), 'positions', ['runs_id'], unique=False)
    op.create_foreign_key('fk_positions_runs_id_runs', 'positions', 'runs', ['runs_id'], ['id'], ondelete='CASCADE')
    op.add_column('trader_trade_data', sa.Column('v_sol_in_bonding_curve', sa.DECIMAL(precision=18, scale=9), nullable=False))
    op.add_column('trader_trade_data', sa.Column('v_tokens_in_bonding_curve', sa.DECIMAL(precision=18, scale=6), nullable=False))
    op.add_column('trader_trade_data', sa.Column('market_cap_sol', sa.DECIMAL(precision=18, scale=9), nullable=False))
    op.add_column('traders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('traders', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traders', 'updated_at')
    op.drop_column('traders', 'created_at')
    op.drop_column('trader_trade_data', 'market_cap_sol')
    op.drop_column('trader_trade_data', 'v_tokens_in_bonding_curve')
    op.drop_column('trader_trade_data', 'v_sol_in_bonding_curve')
    op.drop_constraint('fk_positions_runs_id_runs', 'positions', type_='foreignkey')
    op.drop_index(op.f('ix_positions_runs_id'), table_name='positions')
    op.alter_column('positions', 'traders_id',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False)
    op.drop_column('positions', 'runs_id')
    op.alter_column('mints', 'name',
                    existing_type=sa.String(length=40),
                    type_=sa.VARCHAR(length=30),
                    existing_nullable=True)
    op.drop_column('mints', 'updated_at')
    op.drop_column('mints', 'created_at')
    op.drop_table('run_traders')
    op.drop_table('run_mints')
    op.drop_index(op.f('ix_runs_copy_trading_bots_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_table('copy_trading_bots')

    # Eliminar ENUMs al hacer downgrade
    op.execute("DROP TYPE IF EXISTS side CASCADE")
    op.execute("DROP TYPE IF EXISTS openpositionstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS closeorderstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS partialcloseorderstatus CASCADE")
    # ### end Alembic commands ###
